#!/usr/bin/env bash
#set -x
SNAPCONF="gromox"
#OPTS
BDIR="$(mount |grep nfs|cut -d\  -f3)"
#SIMPLE OR-PATTERN ON ETC-FOLDERS - separate with "\|"
ETCFLDS="grom\|postfix"
RSYNCOPTS="-rvau --partial --delete-after"
MYSQLDUMPOPTS="--single-transaction --routines --triggers --events --add-drop-database"
#Check if dir exists or exit
if grep -qs "${BDIR}" /proc/mounts; then
  echo "NFS-Mount available."
else
  echo "It's not mounted."
  mount "${BDIR}"
  if [ $? -eq 0 ]; then
    echo "Mount success!"
  else
    echo "Something went wrong with the mount..."
    exit 1
  fi
fi

#get mysql-info's and `eval` so they will be available as var
MYSQLCONF="/etc/gromox/mysql_adaptor.cfg"
eval "$(sed 's/ //g' "${MYSQLCONF}")" || echo "[ERROR] ${COMMAND}"

#Gromox-Mount-Path
GROMOXPATH="$(snapper --csvout -c ${SNAPCONF} get-config |sed -n 's/SUBVOLUME,//p')"
#retrieve the latest snapshotpath
#we will copy all from .snapshots/$ID/ to include the info.xml from snapper
SNAPPATH="$GROMOXPATH/.snapshots/$(snapper --csvout -c ${SNAPCONF} list |tail -n1|cut -d, -f3)"

#CREATE BACKUPDIRS
mkdir -p ${BDIR}/{confs,mysql,{fs/"${SNAPCONF}",}} || echo "[ERROR] could not create Directories in ${BDIR}"

#CONFIGS
find /etc -maxdepth 1 -iregex ".*\(${ETCFLDS}\).*" -exec tar -cvJf "${BDIR}/confs/etc.tar.xz" {} +  || echo "[ERROR] config-files"

#MYSQLDUMP
# shellcheck disable=SC2154
COMMAND="mysqldump --user=${mysql_username} --password=${mysql_password} --databases ${mysql_dbname} ${MYSQLDUMPOPTS}"
$COMMAND > "${BDIR}/mysql/${mysql_dbname}.sql" || (echo "[ERROR] ${COMMAND//word=*--data/word= --data}")

#FSCOPY
COMMAND="rsync ${RSYNCOPTS} ${SNAPPATH}/ ${BDIR}/fs/${SNAPCONF}"
time $COMMAND || echo "[ERROR] {COMMAND}"

