#!/usr/bin/env sh
set -e
# https://docs.grommunio.com/admin/operations.html#mail-requeueing
queue="/var/lib/gromox/queue"
j=0
for i in "$queue"/save/*; do
    [ -f "$i" ] || continue
    mv "$i" "$queue"/mess/$j
    j=$((j+1))
    command logger -t gromox-requeue "requeued $i"
done

