#!/bin/bash
# vim:ts=2 sts=2 sw=2 expandtab
set -x
tmp=$(mktemp -d)
doms="$(grommunio-admin domain query domainname | sed '/domainname/d')"
for dom in $doms; do
  mkdir -p $tmp/$dom
  users=$(grommunio-admin user query username status maildir --format json-structured |	jq -r '.[]|select((.username|endswith("'"${dom}"'")) and (.maildir|.!="") and ((.status==0) or (.status==4)))|.username';)
  for usr in $users; do
    echo $usr
    grommunio-admin ldap dump $user > $tmp/$dom/$user.ldif
  done
  # Shared Storages
  for file in $tmp/$dom/*.ldif; do
    user=$(basname $file .ldif)
    if grep -q 'zarafaScharedStorageOnly: 1'; then
      grommunio-admin user modify --status 4 $user
    elif grep -q 'zarafaResourceType: room' ; then
      grommunio-admin exmdb $user store set displaytypeex=7
    elif grep -q 'zarafaResourceType: equipment'; then
      grommunio-admin exmdb $user store set displaytypeex=8
    fi
  done 
done
