#!/bin/sh
[ "$DEBUG" ] && set -x
SRC="$(readlink -f "$0")"
DIR=$(dirname "$SRC")
LINK=$(basename "$0")
FILE="${DIR}/${LINK}.sql"
if [ "${SRC##*/}" = "$LINK" ]; then
	if [ $# -ge 1 ] && [ -f "$1" ]; then
		FILE="$1"
	fi
elif [ -L "$0" ] && [ -f "$FILE" ]; then
	if [ $# -ge 1 ] && [ -f "$1" ]; then

		if [ -r "$DIR/${LINK}.sql" ]; then
			SELECT=$(cat "$DIR/${LINK}.sql")
		fi
	fi
else
	SELECT="pragma integrity_check;"
fi
MQUERY='select username, maildir from users
where maildir like "/var/lib/gromox/user/%"'
if [ $# = 1 ]; then
	USR="$1"
	MQUERY="$MQUERY AND username = \"${USR}\""
fi
VIEWS="$DIR/temp.views"
if ! [ -r "$VIEWS" ]; then
        echo "Temporary Views not found! Exiting!" >/dev/stderr
        exit 1
fi
test -f "$VIEWS"; VIEWS=$(cat "$VIEWS")
command mysql grommunio --skip-column-names \
	--execute="$MQUERY" |
	while read -r username maildir; do
		printf '{ "username": "%s",
		"maildir": "%s",
		"result": %s }\n\n' \
			"$username" "$maildir" \
			"$(printf '%s\n;\n%s\n' "${VIEWS}" "${SELECT}"|
			command sqlite3 -readonly -json \
			"$maildir/exmdb/exchange.sqlite3")";
		done
