#!/usr/bin/env sh
[ "$DEBUG" ] && set -x
SRC="$( readlink -f "$0")"
DIR=$(dirname "$SRC")
LINK=$(basename "$0")
VIEWS=$(cat "$DIR/temp.views")
if [ "$SRC" != "$LINK" ]; then
	if [ -r "$DIR/${LINK}.sql" ]; then
		SELECT=$(cat "$DIR/${LINK}.sql")
	fi
else
	SELECT="pragma integrity_check;"
fi
MQUERY='select username, maildir from users
where maildir like "/var/lib/gromox/user/%"'
if [ $# = 1 ]; then
	USR="$1"
	MQUERY="$MQUERY AND username = \"${USR}\""
fi
command mysql grommunio --skip-column-names \
	--execute="$MQUERY" |
	while read -r username maildir; do
		printf '{ "username": "%s",
		"maildir": "%s",
		"result": %s }\n\n' \
			"$username" "$maildir" \
			"$(echo "${VIEWS};${SELECT}"|
			command sqlite3 -readonly -json \
			"$maildir/exmdb/exchange.sqlite3")";
		done
